### ISSUE TITLE
JavaFX DEB Bundle Without JRE Doesn't Work

### ISSUE THREAD

**Issue by AdamCarroll** [FibreFoX/javafx-gradle-plugin#43] opened 2016-10-08 18:06 UTC
I recently switched the build for [VocabHunter](https://github.com/VocabHunter/VocabHunter) from calling an Ant script to generate the install bundle using your plugin.  The version using your plugin is much simpler.  Well done!

The bundlers I generate are all without the JRE: I expect the user to have installed the JRE.  This works nicely on Mac but on Ubuntu 16.04 I have a problem with the generated DEB file.  It does not work without a hack.  The workaround after installing the DEB is to run the following:
~~~
$ sudo sed -i "s|app.runtime=.*|app.runtime=$JAVA_HOME|g" /opt/VocabHunter/app/VocabHunter.cfg
~~~

Once that is done, the installed application works without a problem.  Do you know of a solution to this?

By the way, this is clearly not a problem caused by your plugin: I had the same problem before I migrated from Ant.  I raise it here in case it is a known problem or you can help.  You can see the issue on my project here: VocabHunter/VocabHunter#6.

**Comment by FibreFoX** [comment] 2016-10-08 19:26
What JDK are you using for bundling here?

**Comment by FibreFoX** [comment] 2016-10-08 19:27
As I'm not familiar with SED, am I reading this right, that you are trying to set environment-variable from `JAVA_HOME`? Is `JAVA_HOME` set for the user?

**Comment by FibreFoX** [comment] 2016-10-08 19:40
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8163356
The detection of the installed JDK mostly depends on environment variables seen by the native launcher, but it fails to detect JRE_HOME.

**Comment by AdamCarroll** [comment] 2016-10-09 09:42
> What JDK are you using for bundling here?

I'm using Oracle JDK 1.8.0_101 when creating the bundle and also when running the application.

Note that I'm not actually bundling the JDK/JRE:
~~~
bundleArguments = [
    ...
    runtime: null
]
~~~

**Comment by AdamCarroll** [comment] 2016-10-09 09:54
> As I'm not familiar with SED, am I reading this right, that you are trying to set environment-variable from JAVA_HOME? Is JAVA_HOME set for the user?

I'm just using Sed to workaround a problem in the generated file `/opt/VocabHunter/app/VocabHunter.cfg`.  Before running the command the `.cfg` file contains the following line:
~~~
app.runtime=
~~~
After running the Sed command it contains the following line which works around the problem:
~~~
app.runtime=/usr/lib/jvm/java-8-oracle
~~~
I'm not actually using the environment variable except as a convenient way to know where Java is installed.  You could re-write the Sed command without it as follows and the result would be the same:
~~~
sudo sed -i "s|app.runtime=.*|app.runtime=/usr/lib/jvm/java-8-oracle|g" /opt/VocabHunter/app/VocabHunter.cfg
~~~

**Comment by FibreFoX** [comment] 2016-10-09 10:56
Starting with some clean Ubuntu-system, how do I reproduce this?

The mechanism with the native launcher without bundled JRE is a bit faulty sometimes when it goes about JAVA_HOME, so I need to reproduce this as best as possible. Personally I'm working on windows-based machines and create some Ubuntu-VM for every bug I recieve.

**Comment by AdamCarroll** [comment] 2016-10-09 12:53
> Starting with some clean Ubuntu-system, how do I reproduce this?

I'm in a similar situation to you except I use a Mac and then have Vagrant/VirtualBox machines for the other two operating systems.  It sounds like you have your Ubuntu set up OK but if you need a hand, give me a shout.  I use the Boxcutter image with Vagrant which works nicely.

To install the Oracle JDK, use the following:
~~~
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
~~~

The quickest way to test if you will see the same problem is to download the latest VocabHunter release which was build using your plugin: https://github.com/VocabHunter/VocabHunter/releases/download/1.0.17/VocabHunter-1.0.17.deb

You can then install the `.deb` using the following command:
~~~
sudo dpkg -i vocabhunter-1.0.17.deb
~~~

Alternatively you can build the `.deb` yourself by cloning the VocabHunter repository and then issuing the following command:
~~~
./gradlew clean build jfxNative checkBundle
~~~

You will find the generated `.deb` file in the directory `package/build/jfx/native`.

**Comment by FibreFoX** [comment] 2016-10-10 11:44
Hi there,

problems solved ;) I now do know what the problem is, and how to fix this!

First I thought it is because of "oracle-java8-set-default" wasn't installed, because this sets `JAVA_HOME` (after reboot, because the script lies inside `/etc/profiles.d/` with the names `jdk.sh` and `jdk.bsh`), but this is not the full truth required to run the application!

Have a look at the used binary file `libpackager.so` which lies aside of the `VocabHunter`-binary, on linux-systems it only checks for **`JRE_HOME`-variable** and not the `JAVA_HOME`-variable.

All you are required is to add some instruction to set this env-variable. Another option would be to compile libpackager.so yourself with adjusted detection-ways. You can cheat a little by looking at this PR: https://github.com/teamfx/openjfx-8u-dev-rt/pull/4

This even is some official JDK-bug: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8163356
This bug was even reported for the javafx-maven-plugin, but it seems some low-priority to fix it on the oracle-side :/

If this "fixes" it for you, please close this issue

**Comment by AdamCarroll** [comment] 2016-10-10 17:51
Hi,

Thanks for looking into this!

What you say about `$JRE_HOME` is clearly right.  If I try from the command line to run the package after install I see this:
~~~
$ /opt/VocabHunter/VocabHunter 
VocabHunter Failed to locate JNI_CreateJavaVM
VocabHunter Failed to launch JVM
~~~

But, if I first run `export JRE_HOME=/usr/lib/jvm/java-8-oracle` and then run the command then it runs without problems.

However, this workaround is clearly going to be problematic for users hoping to run things without the command line.  Do you know if there is a solution to this and a way to make it easy for them to install and run?

**Comment by FibreFoX** [comment] 2016-10-10 18:29
Hi Adam, sorry to say but this is clearly no workaround!
The thing is, what you are experiencing is the caveat of not bundling some JRE. Users will have to setup their systems right, especially advanced users might have some special location for their JRE. The funny part is inside the Ubuntu-help: https://help.ubuntu.com/community/EnvironmentVariables#A.2Fetc.2Fprofile.d.2F.2A.sh

They have the `JAVA_HOME`-variable as example, but that's just for developing.

You now have several options:
* prepare two distributions, one with the JRE bundled, and the other one without, while having some additional setup-instructions for the latter one
* use your own binary modified `libpackager.so` which not only looks for `JRE_HOME`, but for `JAVA_HOME` too, and when not finding anything, looking for some known locations too
* waiting for Oracle to fix this
* set JRE_HOME within customized [`template.postinst`](https://github.com/teamfx/openjfx-8u-dev-rt/blob/7ace46ea46d3751869ba1cc00bd9bdc158982b93/modules/fxpackager/src/main/resources/com/oracle/tools/packager/linux/template.postinst) when using `deb`-bundler (by placing that file into `src/main/deploy/packager/linux/postinst`) ... which might get nasty, never done this before

I would recommend to add this to the installation-documentation!

**Closed by FibreFoX** 2016-10-10 18:29 UTC
Labels: It's the JDK, Linux, native launcher, question, wontfix

**Comment by FibreFoX** [comment] 2016-10-10 18:43
Just one other thing: this problem is not limited to the `deb`-bundler

**Comment by AdamCarroll** [comment] 2016-10-10 19:57
Hi Danny,

Thanks for taking the time to look into this.  At least now I know a bit more about the problem.   I hope Oracle will take a look at the bug that you pointed to.

I appreciate your efforts on this.  Keep up the good work on the Gradle Plugin!
