### ISSUE TITLE
Gradle 3.3 support missing

### ISSUE THREAD

**Issue by StrangeNoises** [FibreFoX/javafx-gradle-plugin#52] opened 2017-01-04 23:16 UTC
Any gradle commands in a project with javafx-gradle-plugin defined as a buildscript dependency fails. Even `gradle tasks`.

The stacktrace suggests the culprit is this plugin (plus other projects that don't use it are building fine):

(Whole stacktrace included for completionism's sake, but pretty sure only the bottom "Caused by" is relevant.)

```
23:05 $ gradle --stacktrace clean

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Joyce'.
> Failed to notify project evaluation listener.
   > org.gradle.internal.classloader.ClasspathUtil.getClasspath(Ljava/lang/ClassLoader;)Ljava/util/List;

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'Joyce'.
        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:55)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
        ... 56 more
Caused by: java.lang.NoSuchMethodError: org.gradle.internal.classloader.ClasspathUtil.getClasspath(Ljava/lang/ClassLoader;)Ljava/util/List;
        at de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePlugin.addJavaFXAntJARToGradleBuildpath(JavaFXGradlePlugin.java:142)
        at de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePlugin.lambda$apply$0(JavaFXGradlePlugin.java:94)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        ... 61 more


BUILD FAILED

Total time: 1.12 secs
```

**Comment by FibreFoX** [comment] 2017-01-04 23:39
It might be that the used API has changed within gradle 3.3. 
Thanks for pointing this out ... I will have to search for some alternative.

**Comment by FibreFoX** [comment] 2017-01-04 23:47
Just checked the API of gradle 3.3 and my thoughts got confirmed! I have to find a different way to check loaded jar-files. Thanks for pointing this out, will work on a fix for this the next days.

**Comment by FibreFoX** [comment] 2017-01-06 08:25
Looking at the `gradle-base-services-3.3.jar` the class seems to still be present ... but has changed their return-type. Lets find something different now ;)

**Comment by FibreFoX** [comment] 2017-01-06 09:26
Hi there, I have found a solution for this, but as I'm currently reworking some parts, some update will be provided for the next week. Will report back when this is available.

**Comment by FibreFoX** [comment] 2017-01-07 16:29
Still working on this, because after making it compile with gradle 3.3 I'm fighting some problem with loading the `ant-jfx.jar`. I hope to get it released in the first half of the next week.

**Comment by ricardojr** [comment] 2017-02-01 08:07
@FibreFoX Any updates?

**Comment by FibreFoX** [comment] 2017-02-01 09:43
This is fixed on master-branch, but not yet released. Sorry for the delay, the javafx-maven-plugin got stucked at some point. Both plugins are using the same workaround for mac-stuff, so I am trying to sync everything ... release is on its way :/ sorry for keeping you waiting.

**Comment by StrangeNoises** [comment] 2017-02-01 12:00
I'm not in a rush. My javafx project has the status of "hobby I'm too busy for right now anyway", while I do some of the boring server-side stuff I actually get paid for. 😂

**Comment by FibreFoX** [comment] 2017-02-01 12:10
@StrangeNoises same for me, but I get frustrated about the current state :) and therefor I'm trying to get some spare time to FINALLY release that stupid ..*rant* *rant*

Will inform you guys when it's released, thanks for your patience anyway.

**Comment by anidotnet** [comment] 2017-02-02 04:44
I am also hit with this issue when upgraded gradle from 3.1 to 3.3. @FibreFoX waiting for your release. Meantime going back to 3.1.

**Comment by FibreFoX** [comment] 2017-02-02 21:09
Hi dear thread-listeners: can you try with current 8.8.0-SNAPSHOT ?

**Comment by vladimirzaytsev** [comment] 2017-02-04 21:13
Good day.
I created simple JavaFX application and run with gradle jfxRun task.

```
0:11:04: Executing external task 'jfxRun'...
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:jfxJar
:jfxRun
Running JavaFX Application
Running command: java -jar project-jfx.jar
Exception in Application constructor
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class com.demo.App
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: com.demo.App.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:818)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
:jfxRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfxRun'.
> There was an exception while executing JavaFX Application. Please check build-log.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.06 secs
There was an exception while executing JavaFX Application. Please check build-log.
0:11:08: External task execution finished 'jfxRun'.
```

**Comment by FibreFoX** [comment] 2017-02-04 21:45
@vladimirzaytsev How dows this relate to gradle 3.3 ? There is a problem with your application, not the javafx-gradle-plugin, please open a separate issue with a sample-project where this can be analyzed.

**Comment by vladimirzaytsev** [comment] 2017-02-05 07:59
@FibreFoX Excuse me, I hastened to conclusions, my mistake. Successfully tested jfxRun and jfxNative tasks with Gradle 3.3 and snapshot version of plugin. Tested on Mac OS X 10.12.3 👍

**Comment by FibreFoX** [comment] 2017-02-05 22:22
Version 8.8.0 got released !

**Closed by FibreFoX** 2017-02-05 22:22 UTC
Labels: bug, Gradle 3
