### ISSUE TITLE
Publish to Gradle Plugin Repository

### ISSUE THREAD

**Issue by JLLeitschuh** [FibreFoX/javafx-gradle-plugin#81] opened 2017-08-06 00:16 UTC
You should publish this plugin to the [Gradle Plugin Repository](https://plugins.gradle.org/) so that it can be accessed within the `plugins` block.

**Comment by FibreFoX** [comment] 2017-08-06 12:53
Duplicate of #69

**Closed by FibreFoX** 2017-08-06 12:53 UTC
