### ISSUE TITLE
JRE bundling

### ISSUE THREAD

**Issue by Lewik** [FibreFoX/javafx-gradle-plugin#9] opened 2016-01-18 07:30 UTC
There are "runtime: null" feature that enable no JRE bundling
It's awesome to reduce size of application

How can I distribute TWO bundles: JRE of needed version and my app? Can all operation systems keep multiple java versions?

The target is reduce update size. So I think I need to distribute not fat jar but separate jars and separate JRE too (JRE with my version).

**Comment by FibreFoX** [comment] 2016-01-18 09:13
The usage of a fat-jar is really not recommended. For distribution you can create native bundles, which do contain the specific JRE, that you are bundling with.

I do know the idea of "not bundling the JRE, because of its size", but it comes with a lot of drawbacks:
* you depend on the user installed JRE, if there isn't any, the application fails
* you depend on the user installed JRE, and you can not check, if the version does work with your application ... otherwise you have to check java-version on startup to make sure there is everything implemented (like dialogs, or other features which came with later update-versions of java)
* you have to test your application with all available java-versions, to make sure being able to reproduce bug-issues
* dependency-hell
* java bugs

The idea behind java-packager is, that you have a full-feature-complete bundle for distribution. If you choose otherwise, you might fail to provide a nice user-experience.

About that "multiple java versions"-question: the runtime is located below the application-folder, the native launcher is checking the generated `.cfg`-file which runtime to choose, and if there is something there, it tries to load DLL-files/SO-files from there. If the runtime isn't specified, the native launcher tries to locate some local installed JRE, if that ultimately fails too, the launcher panics and wont start anything.

To solve your issue:
create two different tasks where you generate both: *with JRE-bundled* and *without JRE-bundled*, but keep in mind that there IS some update-mechanism with some native installers. The generated GUID is random, but can be fixed in two ways (at least for windows):
* by adding the identifier:
```groovy
jfx{
    // choose your GUID to disable random-generation
    identifier = "{7a813ac5-f07e-4134-b879-82be0512eed8}"
}
```
* by copying the first generated installer-source-files (use `--info`-level and set `verbose` to true), the javapackager informs you about the location, which is usually below your temp-folder

If this satisfies your question, please close this issue ;)

**Comment by FibreFoX** [comment] 2016-01-21 14:17
@Lewik any progress on this issue?

**Comment by Lewik** [comment] 2016-01-21 14:57
@FibreFoX I'm to busy at the main work.
We will try this plugin as soon as possible. If you want - you may close question now. I'll try it anyway.

**Closed** 2016-01-21 21:10 UTC
