### ISSUE TITLE
Java 10 jvmArgs not working

### ISSUE THREAD

**Issue by Rykee** [FibreFoX/javafx-gradle-plugin#133] opened 2018-09-19 15:26 UTC
Hey there!
I'm trying to add this jvmArg to my build:
`--add-opens javafx.controls/javafx.scene.control.skin=ALL-UNNAMED`
But when I'm trying to run the installed exe file, the application quits instantly. If I remove the option from the .cfg file it works again.

Relevant part of the cfg file:

`packager.java.version=10.0.2`
`[JVMOptions]`
`--add-opens javafx.controls/javafx.scene.control.skin=ALL-UNNAMED`

In the /runtime/release file: 
`JAVA_VERSION="10.0.2"`

I had the same problem with jfxRun it wouldn't accept this argument. 

Thanks in advance.

Cheers

**Comment by FibreFoX** [comment] 2019-12-08 17:15
Not yet compatible, will be closed as duplicate of #103

**Closed as completed by FibreFoX** 2019-12-08 17:15 UTC
